// data
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_FAIL = 'GET_DATA_FAIL'
export const GET_DATA_LOADING_START = 'GET_DATA_LOADING_START'
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'
export const POST_DATA_FAIL = 'POST_DATA_FAIL'
export const POST_DATA_LOADING_START = 'POST_DATA_LOADING_START'
export const CLEAR_DATA_DATA = 'CLEAR_DATA_DATA'
export const CLEAR_DATA_ERROR = 'CLEAR_DATA_ERROR'